server:
  port: 9502

spring:
  application:
    name: data-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:user}:${MONGODB_PASSWORD:pwd}@${MONGODB_HOST:host}:27017/${MONGODB_DATABASE:db}?&authSource=admin
  profiles:
    active: local
