version: '3'
services:
  mongodb-service:
    image: mongo
    restart: always
    logging:
      options:
        max-size: "10m"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin1
    volumes:
      - ./mongodb-service/mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
      - 9229:9229
    container_name: mongodb-service
  data-service:
    build: ./data-service
    image: kumarch/data-service-img
    ports:
      - "9502:9502"
    depends_on:
      mongodb-service:
        condition: service_started
    environment:
      - MONGODB_HOST=mongodb-service
      - MONGODB_USERNAME=mongoadmin
      - MONGODB_PASSWORD=mongoadmin1
      - MONGODB_DATABASE=mymongodb
    container_name: data-service
