version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    logging:
      options:
        max-size: "10m"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin1
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
      - 9229:9229
    container_name: mongodb-service